# Site settings
course_name: "CSCI2202 Introduction to Programming with Applications for Scientists"
course_description: "This is an introductory, project based, programming course for science majors. The course focuses on programming techniques useful for students in their scientific pursuits. The course introduces basic programming in Python and then goes on to guide students through using simulations, modelling and data-driven analysis. Practical examples will be taken primarily from the fields of microbiology, genomics, neuroscience, and chemistry among others."
course_semester: "Winter 2024-2025"

baseurl: "/scientific_computing" # the subpath of your site, e.g. /blog/
url: "http://maguire-lab.github.io/" # the base hostname & protocol for your site

schoolname: "Dalhousie University"
schoolurl: "https://dalhousie.ca"

address: |
    Room 4242, Mona Campbell Building
    Faculty of Computer Science, Dalhousie University
    Halifax, Nova Scotia

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown
timezone: Canada/Atlantic

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%Y/%m/%d"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
